from selenium import webdriver
import time
print("Doctor booking test case started")
options=webdriver.ChromeOptions()
options.add_experimental_option('excludeSwitches',['enable-logging'])
driver = webdriver.Chrome(options=options)
driver.maximize_window()
driver.get("http://localhost:3000")
driver.find_element("name", "email").send_keys("abhisheksubash25@gmail.com")
time.sleep(3)
print("email entered.")
driver.find_element("name", "password").send_keys("Abhi@1234")
time.sleep(3)
print("password entered.")
driver.find_element("xpath", "/html/body/div[1]/div[1]/div/div[2]/div[1]/div/form/div[1]/button").click()
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[1]/header/div[2]/div/div/div/div[2]/nav/div/ul/li[3]/a").click()
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[1]/div[2]/div/div/div/div[1]/div/div[2]/div/ul/a").click()
time.sleep(3)
driver.get("http://localhost:3000/doctor/6435a74bd0ac21a4528a4453")
time.sleep(3)
driver.find_element("id", "sym").send_keys("Fever")
time.sleep(3)
# driver.find_element("name", "date").send_keys("05/19/2023 10:49 AM")
# time.sleep(3)
driver.find_element("id", "phone").send_keys("7356215600")
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[2]/div/div[2]/div/div[2]/div/div/div[2]/form/button").click()
time.sleep(3)
print("Doctor booked successfully.")