from selenium import webdriver
import time
print("Add to cart test case started")
options=webdriver.ChromeOptions()
options.add_experimental_option('excludeSwitches',['enable-logging'])
driver = webdriver.Chrome(options=options)
driver.maximize_window()
driver.get("http://localhost:3000")
driver.find_element("name", "email").send_keys("abhisheksubash25@gmail.com")
time.sleep(3)
print("email entered.")
driver.find_element("name", "password").send_keys("Abhi@1234")
time.sleep(3)
print("password entered.")
driver.find_element("xpath", "/html/body/div[1]/div[1]/div/div[2]/div[1]/div/form/div[1]/button").click()
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[1]/header/div[2]/div/div/div/div[2]/nav/div/ul/li[2]/a").click()
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[1]/div[3]/div/div/div[1]/div[2]/div/div[1]/div/div[1]").click()
time.sleep(3)
driver.get("http://localhost:3000/product/640d57f33eff4a2fa5f39265")
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[2]/div[1]/div/div/div[1]/div[1]/div/div[2]/div/div[4]/ul/li/button").click()
time.sleep(3)
print("item added to cart.")