from selenium import webdriver
import time
print("Change password test case started")
options=webdriver.ChromeOptions()
options.add_experimental_option('excludeSwitches',['enable-logging'])
driver = webdriver.Chrome(options=options)
driver.maximize_window()
driver.get("http://localhost:3000")
driver.find_element("name", "email").send_keys("abhisheksubash25@gmail.com")
time.sleep(3)
print("email entered.")
driver.find_element("name", "password").send_keys("Abhi@4321")
time.sleep(3)
print("password entered.")
driver.find_element("xpath", "/html/body/div[1]/div[1]/div/div[2]/div[1]/div/form/div[1]/button").click()
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[1]/header/div[1]/div/div/div[3]/div/ul/li[3]/div/ul/li[2]/a/i").click()
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[1]/header/div[1]/div/div/div[3]/div/ul/li[3]/div/ul/li[2]/ul/li[4]/a").click()
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[1]/aside/ul/li[2]/div/button").click()
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[1]/main/div/div/div/section/div/div[2]/div/div/ul/li[3]/button").click()
time.sleep(3)
driver.find_element("name", "currentPassword").send_keys("Abhi@4321")
time.sleep(3)
print("current password entered.")
driver.find_element("name", "newPassword").send_keys("Abhi@1234")
time.sleep(3)
print("new password entered.")
driver.find_element("name", "confirmPassword").send_keys("Abhi@1234")
time.sleep(3)
driver.find_element("xpath", "/html/body/div[1]/div[1]/main/div/div/div/section/div/div[2]/div/div/div/div[3]/div/form/button").click()
time.sleep(3)
print("New password updated entered.")
